language: objective-c
env:
  - CORDOVA_VERSION=latest
  - CORDOVA_VERSION=6.1.1
  - CORDOVA_VERSION=6.0.0
  - CORDOVA_VERSION=5.4.1
  - CORDOVA_VERSION=5.3.3
  - CORDOVA_VERSION=5.2.0
  - CORDOVA_VERSION=5.1.1
  - CORDOVA_VERSION=4.3.0
  - CORDOVA_VERSION=4.2.0
  - CORDOVA_VERSION=4.1.3
  - CORDOVA_VERSION=4.0.1
  - CORDOVA_VERSION=3.7.0
  - CORDOVA_VERSION=3.6.3
  - CORDOVA_VERSION=3.5.0
  - CORDOVA_VERSION=3.4.1
script:
  - npm test
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - echo $JAVA_HOME
  # Install base Android SDK and components
  - export LICENSES="android-sdk-license-c81a61d9|android-sdk-license-ed0d0a5b|android-sdk-license-5be876d5|mips-android-sysimage-license-15de68cc|intel-android-sysimage-license-1ea702d1"
  - export COMPONENTS=android-19,android-20,android-21,android-22,android-23,sys-img-armeabi-v7a-android-19,sys-img-armeabi-v7a-android-21,sys-img-armeabi-v7a-android-22,sys-img-armeabi-v7a-android-23,extra-android-support,addon-google_apis-google-19,google-apis-19,addon-google_apis-google-20,google-apis-20,addon-google_apis-google-21,google-apis-21,addon-google_apis-google-22,google-apis-22,addon-google_apis-google-23,google-apis-23,extra-google-google_play_services,extra-google-gcm,build-tools-19.1.0,build-tools-20.0.1,build-tools-21.0.1,build-tools-22.0.5,build-tools-23.0.2,extra-google-m2repository,extra-android-m2repository
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES
  - source ~/.android-sdk-installer/env
  - android list targets
  # Create and start emulator
  - echo no | android create avd --force -n android-19 -t android-19 --abi armeabi-v7a
  - echo no | android create avd --force -n android-21 -t android-21 --abi armeabi-v7a
  - echo no | android create avd --force -n android-22 -t android-22 --abi armeabi-v7a
  - echo no | android create avd --force -n android-23 -t android-23 --abi armeabi-v7a
  - npm install -g cordova@$CORDOVA_VERSION
  - npm install